Project3/urls.py
from django.contrib import admin
from django.urls import path
from App3 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp/', views.emp),
    path('show/', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>',views.remove),
]

App3/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    contact = models.CharField(max_length=20)

    class Meta:
        db_table = "employee"

App3/forms.py
from django import forms
from App3.models import Employee
class EmployeeForm(forms.ModelForm):
    class Meta:
        model =Employee
        fields ="__all__"

App3/views.py
from django.shortcuts import render,redirect
from App3.forms import EmployeeForm
from App3.models import Employee

# Create your views here.
def emp(request):
    if request.method == "POST":
        form=EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,"index.html",{'form':form})
def show(request):
    employees = Employee.objects.all()
    return render(request,"show.html",{'employees':employees})


def edit(request,id):
    employee = Employee.objects.get(id=id)
    return render(request,'edit.html',{'employee':employee})

def update(request,id):
    employee = Employee.objects.get(id=id)
    form =EmployeeForm(request.POST,instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request,'edit.html',{'employee':employee})
def remove(request,id):
    employee =Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

App3/templates/edit.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
    {% csrf_token %}
    <div class="container">
 <br>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
       <input type="text" name="id" id="id_id" required maxlength="20" value="{{ employee.id }}"/>
    </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
     <input type="text" name="name" id="id_name" required maxlength="20" value="{{ employee.name }}"/>

    </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
     <input type="text" name="email" id="id_email" required maxlength="50" value="{{ employee.email }}"/>

    </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
     <div class="col-sm-4">
     <input type="text" name="contact" id="id_contact" required maxlength="20" value="{{ employee.contact }}"/>
     </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">

    <button type="submit" class="btn btn-success">Update</button>
    </div>
    </div>
    </div>

</form>
</body>
</html>

App3/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


</head>
<body>
<form method="POST" class="post-form" action='/emp/'>
     {% csrf_token %}
<div class="container">
<br>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter details</h3>
    </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label><br>

    <div class="col-sm-4">
    {{form.name}}
    </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label><br>
    <div class="col-sm-4">
    {{ form.email }}
    </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form row">Employee Contact:</label><br>
    <div class="col-sm-4">
    {{ form.contact }}
    </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label><br>
    <div class="col-sm-4">
        <input type="submit" class="btn btn-primary" value="Submit">
    </div>
    </div>
    </div>
</form>
</body>
</html>

App3/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>

<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
    <th>Employee Name</th>
    <th>Employee Email</th>
    <th>Employee Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
     {% for employee in employees %}
    <tr>
    <td>{{ employee.name }}</td>
     <td>{{ employee.email }}</td>
     <td>{{ employee.contact }}</td>
     <td>
        <a href="/edit/{{ employee.id }}"><span class="glyphicon
glyphicon-pencil" >Edit</span></a>
         <a href="/delete/{{ employee.id }}">Delete</a>
     </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
<a href="/emp/" class="btn btn-primary">Add New Record</a>


</body>
</html>